name: ap_psych_demo
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_bloc: ^0.10.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  sass_builder: ^2.1.3
  test: ^1.6.0

  quantaly_lints:
    git:
      url: https://github.com/Quantaly/dart_lints
